// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using onlineShop.Data;

#nullable disable

namespace onlineShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("onlineShop.Models.Client", b =>
                {
                    b.Property<int>("Idclient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Idclient");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idclient"));

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("dateinscrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("motpasse")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("client");

                    b.Property<string>("telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idclient");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("onlineShop.Models.Commande", b =>
                {
                    b.Property<int>("Idcmd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Idcmd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcmd"));

                    b.Property<int>("Idclient")
                        .HasColumnType("int")
                        .HasColumnName("Idclient");

                    b.Property<DateTime>("datecmd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("en cours");

                    b.Property<decimal?>("totalHT")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("totalTTC")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("totalTVA")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Idcmd");

                    b.HasIndex("Idclient");

                    b.ToTable("commande", (string)null);
                });

            modelBuilder.Entity("onlineShop.Models.Facture", b =>
                {
                    b.Property<int>("Idfacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Idfacture");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idfacture"));

                    b.Property<int>("Idcmd")
                        .HasColumnType("int")
                        .HasColumnName("Idcmd");

                    b.Property<DateTime>("dateFac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("numfac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("payée");

                    b.Property<decimal>("totalHT")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("totalTTC")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("totalTVA")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Idfacture");

                    b.HasIndex("Idcmd")
                        .IsUnique();

                    b.HasIndex("numfac")
                        .IsUnique();

                    b.ToTable("Facture", (string)null);
                });

            modelBuilder.Entity("onlineShop.Models.Lignecmd", b =>
                {
                    b.Property<int>("Idligne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Idligne");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idligne"));

                    b.Property<int>("Idcmd")
                        .HasColumnType("int")
                        .HasColumnName("Idcmd");

                    b.Property<int>("Idproduit")
                        .HasColumnType("int")
                        .HasColumnName("Idproduit");

                    b.Property<decimal>("prixtotal")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("prixuni")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("qte")
                        .HasColumnType("int");

                    b.Property<decimal>("tva")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Idligne");

                    b.HasIndex("Idcmd");

                    b.HasIndex("Idproduit");

                    b.ToTable("Lignecmd", (string)null);
                });

            modelBuilder.Entity("onlineShop.Models.Panier", b =>
                {
                    b.Property<int>("Idpanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Idpanier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpanier"));

                    b.Property<DateTime>("DateAjout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dateajout")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime")
                        .HasColumnName("datemodification");

                    b.Property<int>("Idclient")
                        .HasColumnType("int")
                        .HasColumnName("Idclient");

                    b.Property<int>("Idproduit")
                        .HasColumnType("int")
                        .HasColumnName("Idproduit");

                    b.Property<int>("Quantite")
                        .HasColumnType("int")
                        .HasColumnName("quantite");

                    b.HasKey("Idpanier");

                    b.HasIndex("Idproduit");

                    b.HasIndex("Idclient", "Idproduit")
                        .IsUnique()
                        .HasDatabaseName("IX_Panier_UniqueClientProduct");

                    b.ToTable("panier", (string)null);
                });

            modelBuilder.Entity("onlineShop.Models.Produit", b =>
                {
                    b.Property<int>("Idproduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Idproduit");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idproduit"));

                    b.Property<string>("aref")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("cmdLast")
                        .HasColumnType("date");

                    b.Property<string>("codebar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("coli")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("dernmiseajour")
                        .HasColumnType("date");

                    b.Property<string>("design")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("dlc")
                        .HasColumnType("date");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("labo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("prixpub")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("promoweb")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("qtelast")
                        .HasColumnType("int");

                    b.Property<int>("qtestock")
                        .HasColumnType("int");

                    b.Property<decimal?>("tauxtvav")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ttc")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("tva")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("venteHT")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Idproduit");

                    b.HasIndex("codebar")
                        .IsUnique();

                    b.ToTable("produit", (string)null);
                });

            modelBuilder.Entity("onlineShop.Models.Reclamation", b =>
                {
                    b.Property<int>("Idrec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Idrec");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idrec"));

                    b.Property<int>("Idclient")
                        .HasColumnType("int")
                        .HasColumnName("Idclient");

                    b.Property<int?>("Idcmd")
                        .HasColumnType("int")
                        .HasColumnName("Idcmd");

                    b.Property<DateTime>("daterec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("dateresp")
                        .HasColumnType("datetime");

                    b.Property<string>("descrip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reponseAdmin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("en cours");

                    b.Property<string>("sujet")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Idrec");

                    b.HasIndex("Idclient");

                    b.HasIndex("Idcmd");

                    b.ToTable("Reclamation", (string)null);
                });

            modelBuilder.Entity("onlineShop.Models.Commande", b =>
                {
                    b.HasOne("onlineShop.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_commande_ToClient");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("onlineShop.Models.Facture", b =>
                {
                    b.HasOne("onlineShop.Models.Commande", "Commande")
                        .WithOne("Facture")
                        .HasForeignKey("onlineShop.Models.Facture", "Idcmd")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Facture_Tocommande");

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("onlineShop.Models.Lignecmd", b =>
                {
                    b.HasOne("onlineShop.Models.Commande", "Commande")
                        .WithMany("Lignecmds")
                        .HasForeignKey("Idcmd")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Lignecmd_Tocommande");

                    b.HasOne("onlineShop.Models.Produit", "Produit")
                        .WithMany("Lignecmds")
                        .HasForeignKey("Idproduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Lignecmd_ToProduit");

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("onlineShop.Models.Panier", b =>
                {
                    b.HasOne("onlineShop.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Panier_Client");

                    b.HasOne("onlineShop.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("Idproduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Panier_Produit");

                    b.Navigation("Client");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("onlineShop.Models.Reclamation", b =>
                {
                    b.HasOne("onlineShop.Models.Client", "Client")
                        .WithMany("Reclamations")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("onlineShop.Models.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("Idcmd")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("onlineShop.Models.Client", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Reclamations");
                });

            modelBuilder.Entity("onlineShop.Models.Commande", b =>
                {
                    b.Navigation("Facture")
                        .IsRequired();

                    b.Navigation("Lignecmds");
                });

            modelBuilder.Entity("onlineShop.Models.Produit", b =>
                {
                    b.Navigation("Lignecmds");
                });
#pragma warning restore 612, 618
        }
    }
}
